# Generated by Django 2.2.13 on 2023-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbSubject',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=1000)),
                ('is_hot', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbTeacher',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField()),
                ('birth', models.DateField()),
                ('intro', models.CharField(max_length=1000)),
                ('photo', models.CharField(max_length=255)),
                ('gcount', models.IntegerField()),
                ('bcount', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_teacher',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
